### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by Enning94** [Enning94/Doctors_Appointment_Backend#26]
We are 5 in this team @Enning94, @DebyGrey , @VaheStepanyan100 , @adarachel, and @ankitt26 

- Here is a link to the [Kanban board](https://github.com/Enning94/Doctors_Appointment_Backend/projects/1)
- Here is a link to the [repo](https://github.com/Enning94/Doctors_Appointment_Backend)
- screenshot of board
<img width="1427" alt="Screenshot 2023-09-27 at 20 33 48" src="https://github.com/Enning94/Doctors_Appointment_Backend/assets/84347859/7641cdd6-838f-40f4-8b88-bf0aa661d284">

**Comment by Meltrust** [comment]
Hi @DebyGrey 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @Enning94 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project requirements:

![image](https://github.com/Enning94/Doctors_Appointment_Backend/assets/57421823/145cacf0-a609-4e15-bc83-0217c54d96d6)

At the time of this review, these are the pointings:

@adarachel 14
@ankitt26 12
@VaheStepanyan100 16
@Enning94 15
@DebyGrey 10

As you can see, @VaheStepanyan100 has 6 more points than @DebyGrey.  The difference limit is 5.

Kindly, make it so no member of the team has more than 5 points than any other person.

That way, we will meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md). 👍 




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @Enning94 ,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now according to the spec✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
